apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: pulp-operator
  namespace: pulp-repository
spec:
  channel: patch-me-see-overlays-dir
  installPlanApproval: Automatic
  name: pulp-operator
  source: community-operators
  sourceNamespace: openshift-marketplace
  startingCSV: pulp-operator.v1.0.0-alpha.9