---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: odf-lvm-instance
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/cluster-config/odf-lvm-operator/operator/overlays/stable-4.15
    repoURL: https://github.com/tosin2013/sno-quickstarts.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
