apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../base

resources:
  - kafka-cluster.yaml

patches:
  - target:
      kind: Kafka
      name: kafka-cluster
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: my-new-project
      - op: replace
        path: /metadata/name
        value: kafka-new-cluster
  - target:
      kind: Namespace
      name: my-project
    patch: |-
      - op: replace
        path: /metadata/name
        value: my-new-project