---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: amq-streams-operator
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  destination:
    namespace: developer-space
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/cluster-config/amq-streams-operator/operator/overlays/stable
    repoURL:  https://github.com/tosin2013/sno-quickstarts.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true
