apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

bases:
  - ../../base

patchesJson6902:
  - target:
      kind: Pulp
      name: edge-pulp-repo
      namespace: pulp-repository
    path: patch-route.yaml
