---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: openshift-image-registry
  namespace: openshift-gitops
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/cluster-config/openshift-image-registry/overlays/default
    repoURL:  https://github.com/tosin2013/sno-quickstarts.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=false
