apiVersion: v1
kind: Secret
metadata:
  name: 'edge-deployment-pulp-s3'
  namespace: 'pulp-repository'
stringData:
  s3-access-key-id: MAKESEALEDSECRET
  s3-secret-access-key: MAKESEALEDSECRET
  s3-bucket-name: edge-deployment-pulp
  s3-region: us-east-2
