---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ansible-automation-platform-hub
  namespace: openshift-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "3"
spec:
  destination:
    namespace: aap
    server: https://kubernetes.default.svc
  project: default
  source:
    path: gitops/cluster-config/ansible-automation-platform/hub-instance/overlays/default
    repoURL: https://github.com/tosin2013/sno-quickstarts.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: false
    syncOptions:
    - CreateNamespace=true

